# Generated by Django 2.2.3 on 2019-07-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_mc_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='housing_department',
            field=models.CharField(blank=True, max_length=100, verbose_name='ЖЭК'),
        ),
        migrations.AddField(
            model_name='territory',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название территории'),
        ),
    ]
