# Generated by Django 2.2.3 on 2019-07-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_applicationcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='image1',
            field=models.ImageField(blank=True, upload_to='applications'),
        ),
        migrations.AddField(
            model_name='application',
            name='image2',
            field=models.ImageField(blank=True, upload_to='applications'),
        ),
        migrations.AddField(
            model_name='application',
            name='image3',
            field=models.ImageField(blank=True, upload_to='applications'),
        ),
    ]
