# Generated by Django 2.2.3 on 2019-07-20 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_vote_management_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.Vote', verbose_name='Голосование')),
            ],
        ),
    ]
