# Generated by Django 2.2.3 on 2019-07-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190721_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='coordinates1',
            new_name='lat1',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='coordinates2',
            new_name='long1',
        ),
    ]
